import TProduct from "@/types/TProduct";

export const products = [
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "aria",
        model: "Aria AFN1553N Akustik Gitar",
        price: 1500.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/161/afn15-53-n-product-1800x1800.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "aria",
        model: "Aria AWN15BK Akustik Gitar",
        price: 1500.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/156/awn15-bk.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "aria",
        model: "Aria AWN15BLS Akustik Gitar",
        price: 1500.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/155/awn15-bls.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "aria",
        model: "Aria MF240MTTS Akustik Gitar",
        price: 1500.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/700/aria-mf240mtts-akustik-gitar-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABR Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/763/mabr-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MABK Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/761/mabk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "akustik-gitarlar",
        brand: "moon",
        model: "Moon MANT Akustik Gitar",
        price: 1100.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/762/mant-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "elektro-gitarlar",
        brand: "peerless",
        model: "Peerless FIREFOX Standard BK Elektro Gitar",
        price: 3500.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/564/firefoxstandardbk-1.jpg?revision=1697143329",
    },
    {
        category: "gitarlar",
        subCategory: "elektro-gitarlar",
        brand: "peerless",
        model: "Peerless WIZARD Standard BKO Opak Elektro Gitar",
        price: 3500.0,
        image: "https://ideacdn.net/idea/dl/53/myassets/products/691/wizardstanbko-1.jpg?revision=1697143329",
    },
] as TProduct[];
